// Generated by https://quicktype.io

export interface IAthIHS {
  codUsuario: string;
  codEmpresa: string;
  dscEmpresa: string;
  dscEmail: string;
  dscAmbienteApp: string;
  dtaSessao: string;
}
